### PR TITLE
Rename wgWiki* to wgSlackNotificationWiki*

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by Reception123** [comment]
Noting it would be preferable to do this because or else it interferes with other extensions such as DiscordNotifications.

**Comment by kulttuuri** [comment]
Yep. At start all these configs should have been like this, something I did not realize to do.

I am debating whether I should add info to quite close to top of the readme file so that anyone updating to latest version of the extension would notice this change. Potentially this will break anyone updating to latest version if they have changed these parameters. What do you think?

**Comment by paladox** [comment]
> Yep. When I started creating this extension, all these configs should have been named like this. Unfortunately I did not realize this :/
> 
> I am debating whether I should add info to quite close to top of the readme file so that anyone updating to latest version of the extension would notice this change. Potentially this will break anyone updating to latest version if they have changed these parameters. What do you think?

Sounds fine to me :)

**Comment by kulttuuri** [comment]
Thanks! I will now bump the version and make a note of this change.

**Comment by Reception123** [comment]
Thank you for the merge!

**Pull request merged**
